var number = null;

try {
	console.log(number.length);
} catch (e) {console.log(e);console.log('ocorreu um erro')}

console.log('finalizando execucao');